Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
  TargetRubyVersion: 2.3

Style/RedundantSelf:
  Enabled: false

Style/SingleLineBlockParams:
  Enabled: false